return {
  "pablopunk/pi.nvim",
  "vhyrro/luarocks.nvim",
  "git@github.com:TamaMcGlinn/vim-ada",
  "git@github.com:TamaMcGlinn/nvim-alire-tools",
  "tpope/vim-scriptease",
  "dyng/ctrlsf.vim",
  "romainl/vim-cool",
  "yegappan/mru",
  "git@github.com:TamaMcGlinn/vim-termhelp",
  "Owen-Dechow/graph_view_yaml_parser",
  "Owen-Dechow/graph_view_toml_parser",
  "Owen-Dechow/videre.nvim",
  "gbprod/yanky.nvim",
  "git@github.com:TamaMcGlinn/CurtineIncSw.vim",
  "tpope/vim-projectionist",
  "farmergreg/vim-lastplace",
  "ii14/exrc.vim",
  "easymotion/vim-easymotion",
  "https://codeberg.org/andyg/leap.nvim",
  "tpope/vim-repeat",
  "tpope/vim-unimpaired",
  "tpope/vim-surround",
  { "Shougo/vimproc.vim", ["do"] = "make" },
  "dbakker/vim-paragraph-motion",
  "idanarye/vim-vebugger",
  "puremourning/vimspector",
  "sagi-z/vimspectorpy",
  "szw/vim-maximizer",
  "alepez/vim-gtest",
  "simnalamburt/vim-mundo",
  "wfxr/minimap.vim",
  "preservim/tagbar",
  "MunifTanjim/nui.nvim",
  "rcarriga/nvim-notify",
  "lucasdf/hologram.nvim",
  "3rd/image.nvim",
  "kshenoy/vim-signature",
  "nvim-lua/plenary.nvim",
  "nvim-telescope/telescope.nvim",
  "nvim-telescope/telescope-fzy-native.nvim",
  "tknightz/telescope-termfinder.nvim",
  "junegunn/fzf",
  "junegunn/fzf.vim",
  "jesseleite/vim-agriculture",
  "git@github.com:TamaMcGlinn/vim-agtypes",
  "markonm/traces.vim",
  "ThePrimeagen/harpoon",
  "neovim/nvim-lspconfig",
  "p00f/clangd_extensions.nvim",
  "OmniSharp/omnisharp-vim",
  "nickspoons/vim-sharpenup",
  "mason-org/mason.nvim",
  "mason-org/mason-lspconfig.nvim",
  "onsails/lspkind-nvim",
  "hrsh7th/nvim-cmp",
  { "hrsh7th/cmp-nvim-lsp", dependencies = { "hrsh7th/nvim-cmp" } },
  { "hrsh7th/cmp-buffer", dependencies = { "hrsh7th/nvim-cmp" } },
  { "hrsh7th/cmp-path", dependencies = { "hrsh7th/nvim-cmp" } },
  { "hrsh7th/cmp-cmdline", dependencies = { "hrsh7th/nvim-cmp" } },
  "quangnguyen30192/cmp-nvim-ultisnips",
  "lewis6991/hover.nvim",
  "git@github.com:TamaMcGlinn/nvim-lsp-gpr-selector",
  "j5shi/CommandlineComplete.vim",
  "kevinoid/vim-jsonc",
  "ktchen14/cscope-auto",
  "Chiel92/vim-autoformat",
  "git@github.com:TamaMcGlinn/abe-ada-options",
  "tpope/vim-markdown",
  "mikeboiko/vim-markdown-folding",
  "moorereason/vim-markdownfmt",
  { "nvim-treesitter/nvim-treesitter", ["do"] = ":TSUpdate", branch = "main" },
  "briot/tree-sitter-ada",
  "tree-sitter/tree-sitter-typescript",
  "ThePrimeagen/refactoring.nvim",
  "kana/vim-textobj-user",
  { "Julian/vim-textobj-variable-segment", dependencies = { "kana/vim-textobj-user" } },
  "AndrewRadev/sideways.vim",
  "sirver/UltiSnips",
  "honza/vim-snippets",
  "AndrewRadev/switch.vim",
  "MunifTanjim/nui.nvim",
  "git@github.com:TamaMcGlinn/CodeGPT.nvim",
  "archibate/nvim-gpt",
  "git@github.com:TamaMcGlinn/vim-sanergx",
  "morhetz/gruvbox",
  "glexey/visSum.vim",
  "vim-airline/vim-airline",
  "tomtom/tcomment_vim",
  "mhinz/vim-startify",
  "google/vim-maktaba",
  { "bazelbuild/vim-bazel", dependencies = { "google/vim-maktaba" } },
  "git@github.com:TamaMcGlinn/vim-bazeljump",
  "Zeioth/compiler.nvim",
  "Zeioth/makeit.nvim",
  { "google/vim-glaive", dependencies = { "google/vim-maktaba" } },
  { "google/vim-codefmt", dependencies = { "google/vim-maktaba" } },
  "AndrewRadev/splitjoin.vim",
  "adelarsq/vim-matchit",
  "nvim-treesitter/nvim-treesitter-context",
  "farmergreg/vim-lastplace",
  "git@github.com:TamaMcGlinn/vim-mkplugin",
  "RishabhRD/popfix",
  "RishabhRD/nvim-cheat.sh",
  "mattn/calendar-vim",
  "vimwiki/vimwiki",
  "sk1418/HowMuch",
  "junegunn/vim-easy-align",
  "mhinz/vim-signify",
  "tpope/vim-rhubarb",
  "shumphrey/fugitive-gitlab.vim",
  "git@github.com:TamaMcGlinn/vim-gerritbrowse",
  "psliwka/vim-smoothie",
  "akinsho/toggleterm.nvim",
  "git@github.com:TamaMcGlinn/vim-termhere",
  "git@github.com:TamaMcGlinn/vim-dirhere",
  "git@github.com:TamaMcGlinn/vim-browsedir",
  "liuchengxu/vim-which-key",
  "liuchengxu/vim-clap",
  "sodapopcan/vim-twiggy",
  "stsewd/fzf-checkout.vim",
  "rhysd/conflict-marker.vim",
  "rhysd/git-messenger.vim",
  "aacunningham/vim-fuzzy-stash",
  "nvim-tree/nvim-web-devicons",
  "sindrets/diffview.nvim",
  "git@github.com:TamaMcGlinn/vim-git-essentials",
  "git@github.com:TamaMcGlinn/git-worktree.nvim",
  "Juksuu/worktrees.nvim",
  "git@github.com:TamaMcGlinn/vim-gitcycle",
  { "git@github.com:TamaMcGlinn/vim-fugitive", branch = "footbazooka" },
  { "rbong/vim-flog", tag = "v3.0.0" },
  "skywind3000/vim-quickui",
  "git@github.com:TamaMcGlinn/flog-menu",
  "git@github.com:TamaMcGlinn/flog-teamjump",
  { "git@github.com:TamaMcGlinn/flog-navigate", dependencies = { "rbong/vim-flog" } },
  "git@github.com:TamaMcGlinn/vim-autoflog",
  "git@github.com:TamaMcGlinn/vim-instaflog",
  {
    "git@github.com:TamaMcGlinn/vim-floggit-keybindings",
    dependencies = { "liuchengxu/vim-which-key", "rbong/vim-flog" },
    url = "git@github.com:TamaMcGlinn/vim-floggit-keybindings",
  },
  "dsummersl/vimunit",
  "int3/vim-extradite",
  "chrisbra/SudoEdit.vim",
  "roggan87/vim-bible",
  "git@github.com:TamaMcGlinn/quickfixdd",
  "folke/trouble.nvim",
  "tpope/vim-eunuch",
  "justinmk/vim-dirvish",
  "kristijanhusak/vim-dirvish-git",
  "roginfarrer/vim-dirvish-dovish",
  "bounceme/remote-viewer",
  "vuciv/golf",
  "voldikss/vim-floaterm",
  "git@github.com:TamaMcGlinn/vim-bettergf",
  "git@github.com:TamaMcGlinn/vim-gitremotes",
  "uga-rosa/translate.nvim",
  "git@github.com:TamaMcGlinn/vim-fuzzy-recent",
  "ryanoasis/vim-devicons",
}
